spring.application.name=StockMarket
spring.config.import=optional:file:.env[.properties]

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://stockmarket-db:5432/stockmarket}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${SERVER_PORT:8080}
