spring.application.name=StockMarket
spring.config.import=optional:file:.env\[.properties\]

# Database configuration
spring.datasource.url=jdbc:h2:mem:stock_market_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver